### ISSUE TITLE
jambagecom/base-enum ^0.0 -> could not be found

### ISSUE THREAD

**Issue by phil64** [franzholz/base_zip#1]
On composer installation: 
`jambagecom/base-zip v0.0.1 requires jajambagecom/base-zip v0.0.1 requires jambagecom/base-enum ^0.0 -> could not be found in any version, there may be a typo in the package namembagecom/base-enum ^0.0 -> could not be found in any version, there may be a typo in the package name`

**Comment by franzholz** [comment]
I have added the missing package base_enum now:

https://packagist.org/packages/jambagecom/base-enum
